version: '3.6'

services:
  opengpt:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env.local
  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file:
      - .env.local

volumes:
  mongodb-data:
    name: opengpt-mongodb-data
  mongodb-configdb:
    name: opengpt-mongodb-configdb
